insert into authors (id, first_name, last_name) values (1, 'Esbjörn', 'Lipson');
insert into authors (id, first_name, last_name) values (2, 'Bécassine', 'Philcott');
insert into authors (id, first_name, last_name) values (3, 'Séréna', 'Liddall');
insert into authors (id, first_name, last_name) values (4, 'Yénora', 'Fennelow');
insert into authors (id, first_name, last_name) values (5, 'Angèle', 'Crebott');
insert into authors (id, first_name, last_name) values (6, 'Mélanie', 'Ludwikiewicz');
insert into authors (id, first_name, last_name) values (7, 'Maï', 'Mahaddy');
insert into authors (id, first_name, last_name) values (8, 'Maéna', 'Minter');
insert into authors (id, first_name, last_name) values (9, 'Björn', 'Reboulet');
insert into authors (id, first_name, last_name) values (10, 'Léandre', 'Ellams');
insert into authors (id, first_name, last_name) values (11, 'Faîtes', 'Chessil');
insert into authors (id, first_name, last_name) values (12, 'Annotés', 'Grzesiak');
insert into authors (id, first_name, last_name) values (13, 'Faîtes', 'Felder');
insert into authors (id, first_name, last_name) values (14, 'Illustrée', 'Scorrer');
insert into authors (id, first_name, last_name) values (15, 'Irène', 'Guinane');
insert into authors (id, first_name, last_name) values (16, 'Östen', 'Annable');
insert into authors (id, first_name, last_name) values (17, 'Illustrée', 'Bayston');
insert into authors (id, first_name, last_name) values (18, 'Bérangère', 'Hellin');
insert into authors (id, first_name, last_name) values (19, 'Camélia', 'Simoni');
insert into authors (id, first_name, last_name) values (20, 'Örjan', 'Durran');
insert into authors (id, first_name, last_name) values (21, 'Björn', 'Wondraschek');
insert into authors (id, first_name, last_name) values (22, 'Erwéi', 'Stearns');
insert into authors (id, first_name, last_name) values (23, 'Kallisté', 'Edwick');
insert into authors (id, first_name, last_name) values (24, 'Gérald', 'McKerley');
insert into authors (id, first_name, last_name) values (25, 'Maïwenn', 'Fyndon');
insert into authors (id, first_name, last_name) values (26, 'Vénus', 'Slograve');
insert into authors (id, first_name, last_name) values (27, 'Léana', 'Brabant');
insert into authors (id, first_name, last_name) values (28, 'Tú', 'Zuanelli');
insert into authors (id, first_name, last_name) values (29, 'Kuí', 'Sandon');
insert into authors (id, first_name, last_name) values (30, 'Kuí', 'Pyford');
insert into authors (id, first_name, last_name) values (31, 'Cléa', 'Farlham');
insert into authors (id, first_name, last_name) values (32, 'Maïwenn', 'Knowlton');
insert into authors (id, first_name, last_name) values (33, 'Zhì', 'Baudin');
insert into authors (id, first_name, last_name) values (34, 'Garçon', 'Antoniottii');
insert into authors (id, first_name, last_name) values (35, 'Camélia', 'Boshard');
insert into authors (id, first_name, last_name) values (36, 'Aí', 'Furman');
insert into authors (id, first_name, last_name) values (37, 'Adèle', 'Tander');
insert into authors (id, first_name, last_name) values (38, 'Laïla', 'Willatt');
insert into authors (id, first_name, last_name) values (39, 'Andrée', 'Font');
insert into authors (id, first_name, last_name) values (40, 'Maïlis', 'Alenshev');
insert into authors (id, first_name, last_name) values (41, 'Angèle', 'Coslitt');
insert into authors (id, first_name, last_name) values (42, 'Annotés', 'Shafier');
insert into authors (id, first_name, last_name) values (43, 'Yú', 'Das');
insert into authors (id, first_name, last_name) values (44, 'Ruì', 'Lake');
insert into authors (id, first_name, last_name) values (45, 'Edmée', 'Corlett');
insert into authors (id, first_name, last_name) values (46, 'Garçon', 'Wyllis');
insert into authors (id, first_name, last_name) values (47, 'Nadège', 'Jacobsson');
insert into authors (id, first_name, last_name) values (48, 'Tán', 'Snary');
insert into authors (id, first_name, last_name) values (49, 'Maëly', 'Liddard');
insert into authors (id, first_name, last_name) values (50, 'Marie-thérèse', 'Sarath');
insert into authors (id, first_name, last_name) values (51, 'Léana', 'Renouf');
insert into authors (id, first_name, last_name) values (52, 'Eliès', 'Rubenczyk');
insert into authors (id, first_name, last_name) values (53, 'Marie-françoise', 'Harpham');
insert into authors (id, first_name, last_name) values (54, 'Cécile', 'Kubin');
insert into authors (id, first_name, last_name) values (55, 'Faîtes', 'Blondin');
insert into authors (id, first_name, last_name) values (56, 'Clémentine', 'Kryszkiecicz');
insert into authors (id, first_name, last_name) values (57, 'Chloé', 'Squire');
insert into authors (id, first_name, last_name) values (58, 'Françoise', 'Barrasse');
insert into authors (id, first_name, last_name) values (59, 'Méline', 'Firby');
insert into authors (id, first_name, last_name) values (60, 'Loïca', 'Waterdrinker');
insert into authors (id, first_name, last_name) values (61, 'Yè', 'Sancroft');
insert into authors (id, first_name, last_name) values (62, 'Salomé', 'Rawdall');
insert into authors (id, first_name, last_name) values (63, 'Faîtes', 'Mapston');
insert into authors (id, first_name, last_name) values (64, 'Gisèle', 'Melmoth');
insert into authors (id, first_name, last_name) values (65, 'Estève', 'Jocic');
insert into authors (id, first_name, last_name) values (66, 'Marie-noël', 'Broadstock');
insert into authors (id, first_name, last_name) values (67, 'Gwenaëlle', 'Corless');
insert into authors (id, first_name, last_name) values (68, 'Médiamass', 'Gaunt');
insert into authors (id, first_name, last_name) values (69, 'Ophélie', 'Garrood');
insert into authors (id, first_name, last_name) values (70, 'Pål', 'Nolda');
insert into authors (id, first_name, last_name) values (71, 'Eugénie', 'Spellecy');
insert into authors (id, first_name, last_name) values (72, 'Nuó', 'Broadfoot');
insert into authors (id, first_name, last_name) values (73, 'Camélia', 'Bendle');
insert into authors (id, first_name, last_name) values (74, 'Béatrice', 'Besse');
insert into authors (id, first_name, last_name) values (75, 'Méghane', 'Jurick');
insert into authors (id, first_name, last_name) values (76, 'Irène', 'Beynke');
insert into authors (id, first_name, last_name) values (77, 'Géraldine', 'Dominici');
insert into authors (id, first_name, last_name) values (78, 'Clélia', 'Pomphrey');
insert into authors (id, first_name, last_name) values (79, 'Mélys', 'Fry');
insert into authors (id, first_name, last_name) values (80, 'Pål', 'Goodbur');
insert into authors (id, first_name, last_name) values (81, 'Géraldine', 'Farmer');
insert into authors (id, first_name, last_name) values (82, 'Ráo', 'Boom');
insert into authors (id, first_name, last_name) values (83, 'Noëlla', 'Overshott');
insert into authors (id, first_name, last_name) values (84, 'Estève', 'Breckell');
insert into authors (id, first_name, last_name) values (85, 'Léane', 'O''Fielly');
insert into authors (id, first_name, last_name) values (86, 'Bénédicte', 'Lattimore');
insert into authors (id, first_name, last_name) values (87, 'Yáo', 'Licari');
insert into authors (id, first_name, last_name) values (88, 'Ruì', 'Hammerson');
insert into authors (id, first_name, last_name) values (89, 'Réjane', 'Chansonnau');
insert into authors (id, first_name, last_name) values (90, 'Lài', 'Sposito');
insert into authors (id, first_name, last_name) values (91, 'Hélène', 'Kneel');
insert into authors (id, first_name, last_name) values (92, 'Amélie', 'Rakestraw');
insert into authors (id, first_name, last_name) values (93, 'Illustrée', 'Pickburn');
insert into authors (id, first_name, last_name) values (94, 'Maëlys', 'Shelborne');
insert into authors (id, first_name, last_name) values (95, 'Uò', 'Cockerill');
insert into authors (id, first_name, last_name) values (96, 'Hélène', 'Stranieri');
insert into authors (id, first_name, last_name) values (97, 'Anaé', 'Eastcott');
insert into authors (id, first_name, last_name) values (98, 'Nuó', 'Cruise');
insert into authors (id, first_name, last_name) values (99, 'Maëline', 'Gove');
insert into authors (id, first_name, last_name) values (100, 'Mélys', 'Cudde');

insert into books (id, title, price_old, price, author_id) values (1, 'Stringtough', 2659, 1688, 79);
insert into books (id, title, price_old, price, author_id) values (2, 'Stringtough', 2815, 1285, 77);
insert into books (id, title, price_old, price, author_id) values (3, 'Gembucket', 2646, 3095, 11);
insert into books (id, title, price_old, price, author_id) values (4, 'Overhold', 2918, 3104, 53);
insert into books (id, title, price_old, price, author_id) values (5, 'Tresom', 2693, 1049, 23);
insert into books (id, title, price_old, price, author_id) values (6, 'Gembucket', 1276, 1849, 72);
insert into books (id, title, price_old, price, author_id) values (7, 'Latlux', 705, 2088, 21);
insert into books (id, title, price_old, price, author_id) values (8, 'Regrant', 989, 3173, 12);
insert into books (id, title, price_old, price, author_id) values (9, 'Biodex', 2400, 2279, 87);
insert into books (id, title, price_old, price, author_id) values (10, 'Ventosanzap', 1174, 3678, 21);
insert into books (id, title, price_old, price, author_id) values (11, 'Konklux', 1435, 1904, 50);
insert into books (id, title, price_old, price, author_id) values (12, 'Viva', 1714, 2568, 62);
insert into books (id, title, price_old, price, author_id) values (13, 'Prodder', 2547, 1541, 95);
insert into books (id, title, price_old, price, author_id) values (14, 'Transcof', 1871, 2718, 43);
insert into books (id, title, price_old, price, author_id) values (15, 'Latlux', 563, 4775, 7);
insert into books (id, title, price_old, price, author_id) values (16, 'Tres-Zap', 2630, 2793, 27);
insert into books (id, title, price_old, price, author_id) values (17, 'Flowdesk', 1112, 2673, 90);
insert into books (id, title, price_old, price, author_id) values (18, 'Cookley', 1147, 4442, 57);
insert into books (id, title, price_old, price, author_id) values (19, 'Zathin', 2413, 2706, 78);
insert into books (id, title, price_old, price, author_id) values (20, 'Voyatouch', 2404, 4741, 39);
insert into books (id, title, price_old, price, author_id) values (21, 'Overhold', 1152, 1454, 1);
insert into books (id, title, price_old, price, author_id) values (22, 'Prodder', 1450, 4821, 100);
insert into books (id, title, price_old, price, author_id) values (23, 'Bitchip', 841, 3145, 68);
insert into books (id, title, price_old, price, author_id) values (24, 'Latlux', 1809, 4418, 56);
insert into books (id, title, price_old, price, author_id) values (25, 'Solarbreeze', 2944, 3504, 60);
insert into books (id, title, price_old, price, author_id) values (26, 'Alpha', 2866, 1855, 77);
insert into books (id, title, price_old, price, author_id) values (27, 'Zamit', 1372, 3872, 74);
insert into books (id, title, price_old, price, author_id) values (28, 'Biodex', 2348, 1857, 83);
insert into books (id, title, price_old, price, author_id) values (29, 'Home Ing', 1901, 3697, 7);
insert into books (id, title, price_old, price, author_id) values (30, 'Asoka', 590, 1245, 41);
insert into books (id, title, price_old, price, author_id) values (31, 'Treeflex', 2993, 2718, 91);
insert into books (id, title, price_old, price, author_id) values (32, 'Prodder', 2104, 3640, 67);
insert into books (id, title, price_old, price, author_id) values (33, 'Tempsoft', 2024, 1598, 6);
insert into books (id, title, price_old, price, author_id) values (34, 'Tin', 2373, 4493, 48);
insert into books (id, title, price_old, price, author_id) values (35, 'Rank', 2772, 3451, 48);
insert into books (id, title, price_old, price, author_id) values (36, 'Otcom', 1331, 1588, 93);
insert into books (id, title, price_old, price, author_id) values (37, 'Matsoft', 805, 1351, 99);
insert into books (id, title, price_old, price, author_id) values (38, 'Andalax', 2259, 2769, 58);
insert into books (id, title, price_old, price, author_id) values (39, 'Rank', 2252, 4872, 37);
insert into books (id, title, price_old, price, author_id) values (40, 'Daltfresh', 925, 1488, 80);
insert into books (id, title, price_old, price, author_id) values (41, 'Zathin', 1190, 3909, 54);
insert into books (id, title, price_old, price, author_id) values (42, 'Namfix', 909, 4532, 36);
insert into books (id, title, price_old, price, author_id) values (43, 'Transcof', 1479, 4168, 48);
insert into books (id, title, price_old, price, author_id) values (44, 'Trippledex', 790, 3279, 94);
insert into books (id, title, price_old, price, author_id) values (45, 'Latlux', 1105, 4594, 14);
insert into books (id, title, price_old, price, author_id) values (46, 'Zamit', 2554, 4219, 50);
insert into books (id, title, price_old, price, author_id) values (47, 'Flexidy', 692, 3666, 88);
insert into books (id, title, price_old, price, author_id) values (48, 'Rank', 592, 3179, 11);
insert into books (id, title, price_old, price, author_id) values (49, 'Flowdesk', 1965, 1410, 29);
insert into books (id, title, price_old, price, author_id) values (50, 'Asoka', 1824, 3300, 4);
insert into books (id, title, price_old, price, author_id) values (51, 'Sonsing', 1119, 1756, 89);
insert into books (id, title, price_old, price, author_id) values (52, 'Home Ing', 920, 4193, 60);
insert into books (id, title, price_old, price, author_id) values (53, 'Veribet', 2542, 2738, 66);
insert into books (id, title, price_old, price, author_id) values (54, 'Regrant', 902, 4411, 47);
insert into books (id, title, price_old, price, author_id) values (55, 'Temp', 2369, 1100, 2);
insert into books (id, title, price_old, price, author_id) values (56, 'Asoka', 2513, 3474, 26);
insert into books (id, title, price_old, price, author_id) values (57, 'Veribet', 1936, 3528, 77);
insert into books (id, title, price_old, price, author_id) values (58, 'Matsoft', 2696, 2285, 20);
insert into books (id, title, price_old, price, author_id) values (59, 'Pannier', 2517, 4676, 85);
insert into books (id, title, price_old, price, author_id) values (60, 'Ronstring', 639, 4306, 72);
insert into books (id, title, price_old, price, author_id) values (61, 'Y-find', 1502, 2786, 90);
insert into books (id, title, price_old, price, author_id) values (62, 'Bytecard', 2231, 4590, 50);
insert into books (id, title, price_old, price, author_id) values (63, 'Cardify', 1117, 3743, 84);
insert into books (id, title, price_old, price, author_id) values (64, 'Sonsing', 1408, 2204, 44);
insert into books (id, title, price_old, price, author_id) values (65, 'Cardguard', 647, 3119, 40);
insert into books (id, title, price_old, price, author_id) values (66, 'Y-find', 1212, 1863, 60);
insert into books (id, title, price_old, price, author_id) values (67, 'Pannier', 2253, 1422, 55);
insert into books (id, title, price_old, price, author_id) values (68, 'Andalax', 2040, 4891, 96);
insert into books (id, title, price_old, price, author_id) values (69, 'Voltsillam', 1984, 4557, 54);
insert into books (id, title, price_old, price, author_id) values (70, 'Hatity', 2252, 3948, 47);
insert into books (id, title, price_old, price, author_id) values (71, 'Bitchip', 857, 1438, 79);
insert into books (id, title, price_old, price, author_id) values (72, 'Tampflex', 1533, 1456, 77);
insert into books (id, title, price_old, price, author_id) values (73, 'Holdlamis', 1243, 4070, 62);
insert into books (id, title, price_old, price, author_id) values (74, 'Fintone', 1349, 4798, 82);
insert into books (id, title, price_old, price, author_id) values (75, 'Ventosanzap', 1397, 1379, 55);
insert into books (id, title, price_old, price, author_id) values (76, 'Aerified', 1345, 1696, 5);
insert into books (id, title, price_old, price, author_id) values (77, 'Viva', 1372, 3122, 8);
insert into books (id, title, price_old, price, author_id) values (78, 'Bigtax', 1708, 1056, 89);
insert into books (id, title, price_old, price, author_id) values (79, 'Latlux', 2475, 4863, 58);
insert into books (id, title, price_old, price, author_id) values (80, 'Voyatouch', 2473, 3816, 50);
insert into books (id, title, price_old, price, author_id) values (81, 'Y-find', 573, 1775, 29);
insert into books (id, title, price_old, price, author_id) values (82, 'Zontrax', 1443, 3913, 92);
insert into books (id, title, price_old, price, author_id) values (83, 'Prodder', 1083, 3994, 71);
insert into books (id, title, price_old, price, author_id) values (84, 'Keylex', 2738, 2781, 92);
insert into books (id, title, price_old, price, author_id) values (85, 'Home Ing', 935, 4803, 96);
insert into books (id, title, price_old, price, author_id) values (86, 'Veribet', 1939, 4282, 99);
insert into books (id, title, price_old, price, author_id) values (87, 'Tempsoft', 1338, 4083, 61);
insert into books (id, title, price_old, price, author_id) values (88, 'Overhold', 609, 4306, 95);
insert into books (id, title, price_old, price, author_id) values (89, 'Trippledex', 2958, 3712, 47);
insert into books (id, title, price_old, price, author_id) values (90, 'Overhold', 1002, 4734, 27);
insert into books (id, title, price_old, price, author_id) values (91, 'Opela', 2838, 2510, 67);
insert into books (id, title, price_old, price, author_id) values (92, 'Alphazap', 2517, 4527, 99);
insert into books (id, title, price_old, price, author_id) values (93, 'Overhold', 1525, 2466, 70);
insert into books (id, title, price_old, price, author_id) values (94, 'Quo Lux', 574, 3756, 16);
insert into books (id, title, price_old, price, author_id) values (95, 'Cardify', 1188, 3665, 85);
insert into books (id, title, price_old, price, author_id) values (96, 'Namfix', 1595, 1991, 13);
insert into books (id, title, price_old, price, author_id) values (97, 'Toughjoyfax', 1295, 2240, 34);
insert into books (id, title, price_old, price, author_id) values (98, 'Konklab', 1151, 4169, 92);
insert into books (id, title, price_old, price, author_id) values (99, 'Fixflex', 1593, 3292, 82);
insert into books (id, title, price_old, price, author_id) values (100, 'It', 2191, 1985, 65);


